
import "~/styles/globals.css";
import Link from "next/link";
import { type Metadata } from "next";
import { Geist } from "next/font/google";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geist.variable}`}>
            <div className="items-start flex flex-row gap-x-2 w-full h-10 bg-black join">
              <Link href="/"><button className="join-item btn bg-[#000000] text-white border-[#e5e5e5]">Home</button></Link>
              <Link href="/layer02"><button className="join-item  btn bg-[#000000] text-white border-[#e5e5e5]">About</button></Link>
              <Link href="/layer03"><button className="join-item  btn bg-[#000000] text-white border-[#e5e5e5]">Database</button></Link>
              <Link href="/layer04"><button className="join-item btn bg-[#000000] text-white border-[#e5e5e5]">Secret Page 4</button></Link>
            </div>
        {children}
      </body>
    </html>
  );
}

